# Generated by Django 5.0 on 2024-02-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='lab.category'),
        ),
    ]
