# Generated by Django 5.0 on 2024-03-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_remove_product_weight_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at']},
        ),
    ]
